### ISSUE TITLE
OCToolBox crashes when selecting Device tab

### ISSUE THREAD

**Issue by perez987** [webfalter/OCToolBox#3]
Good afternoon. OCToolBox is a very useful app for all OpenCore users. But I've have an issue: every time I try to go to the Device tab, the app crashes. Everything else works perfectly.

I'm on macOS Ventura (tried 13.3.1 and 13.4b).

Anyway, thanks for your work.

[crash-report.txt](https://github.com/webfalter/OCToolBox/files/11338046/crash-report.txt)

**Comment by webfalter** [comment]
@perez987 
Can you read the output from https://github.com/acidanthera/gfxutil/releases
./gfxutil -f hdef
./gfxutil -f GFX0
./gfxutil -f igpu

And write your hardware

**Comment by perez987** [comment]
@webfalter 
I’m not at home. I’ll do it on Tuesday. Thanks.

**Comment by perez987** [comment]
@webfalter 
Tried again OCToolBox 0.9.4, no changes, app crashes when selecting Device tab, all other tabs work properly.

```
gfxutil -f hdef
00:1f.3 8086:a348 /PCI0@0/HDEF@1F,3 = PciRoot(0x0)/Pci(0x1F,0x3)

gfxutil -f GFX0
03:00.0 1002:73ff /PCI0@0/PEG0@1/PEGP@0/BRG0@0/GFX0@0 = PciRoot(0x0)/Pci(0x1,0x0)/Pci(0x0,0x0)/Pci(0x0,0x0)/Pci(0x0,0x0)

gfxutil -f igpu
DevicePath not found!
(MacPro7,1 or iMacPro1,1 SMBIOS, iGPU disabled in BIOS).
```

My system: Z390 + i9-9900K + RX 6600 XT + Sonoma DP1 or Ventura 13.4.

**Comment by perez987** [comment]
@webfalter 
More info, this may be where the error originates.
If I enable iGPU in BIOS and use iMac19.1 SMBIOS:
- iGPU is seen with gfxutil
```
gfxutil -f igpu
00:02.0 8086:3e9b /PCI0@0/IGPU@2 = PciRoot(0x0)/Pci(0x2,0x0)
```
- Device tab works fine, app doesn't crash.
<img width="550" alt="device-gpu" src="https://github.com/webfalter/OCToolBox/assets/50429399/1f313a2b-9cb2-4278-af3e-118284042f47">


Note: `Auswahl` and `Grafik`are not translated when the app runs in English.

**Comment by perez987** [comment]
@webfalter 
Closing issue as it seems to be known. When no iGFX is present, device tab crashes. Please fix this. I really like this app.

**Comment by webfalter** [comment]
Be patient for a few more days, tinker around a bit. Sorry I don't have the time.
![Bildschirmfoto 2023-06-27 um 16 43 09](https://github.com/webfalter/OCToolBox/assets/481551/a5ec13e9-f2b4-46bd-adc9-6dcf1bc11e23)
