### ISSUE TITLE
Feature Suggestion: Add Framebuffer Flags Calculator

### ISSUE THREAD

**Issue by 5T33Z0** [webfalter/OCToolBox#4]
Wäre es möglich einen Calculator for Framebuffer Flags einzubauen, die man für die Property `framebuffer-conx-flags` verwenden kann?  Mir ist bewusst, dass Hackintool das auch kann. Was man mit Hackintool allerdings NICHT machen kann, ist einen _bekannten Wert_ eingeben, um herauszufinden, um welche flags es sich handelt. Zudem ist die Bedienung in dem kleinen Programmfenster von Hackintool nicht so schön und übersichtlich.

## Framebuffer Flags
Anbei sind die möglich flags aufgelistet. Die Beschreibungen einfach ignorieren.

`#`|Name                        | Description | Hex Value
:-:|----------------------------|-------------|:----------:
01 |**`FBAvoidFastLinkTraining`** | Sets the logic of `minStolenMem` calculation, when set StolenMemorySize is not multiplied by FBMemoryCount, assuming StolenMemorySize counts all framebuffers at once. | 0x1
02 |**`FBFramebufferCommonMemory`**  | This is equivalent to setting FBC=1 in the plist FeatureControl section. | 0x2
03 |**`FBFramebufferCompression`** |Equivalent to setting `SliceSDEnable=1`, `EUSDEnable=1`, `DynamicSliceSwitch=1` in the plist FeatureControl section. | 0x4
04 |**`FBEnableSliceFeatures`** | Equivalent to setting `DynamicFBCEnable=1` in the plist FeatureControl section |0x8
05 |**`FBDynamicFBCEnable`** |Sets `fUseVideoTurbo=1` and loads GPU turbo frequency from the specific field. Defaults to 14, can be overridden by `VideoTurboFreq` in the plist FeatureControl section.|0x10
06 |**`FBUseVideoTurbo`**       | |0x20
07 |**`FBForcePowerAlwaysConnected`** | |0x40
08 |**`FBDisableHighBitrateMode2`**   | |0x80
09 |**`FBBoostPixelFrequencyLimit`**  | |0x100
10 |**`FBLimit4KSourceSize`**         | |0x200
11 |**`FBAlternatePWMIncrement1`**    | |0x400
12 |**`FBAlternatePWMIncrement2`**    | |0x800
13 |**`FBDisableFeatureIPS`**         | |0x1000
14 |**`FBUnknownFlag_2000`**          | |0x2000
15 |**`FBAllowConnectorRecover`**     | |0x4000
16 |**`FBUnknowFlag_8000`**           | |0x8000
17 |**`FBUnknowFlag_10000`**          | |0x10000
18 |**`FBUnknownFlag_20000`**         | |0x20000
19 |**`FBDisableGFMPPFM`**            | |0x40000
20 |**`FBUnknownFlag_80000`**         | |0x80000
21 |**`FBUnknownFlag_100000`**        | |0x100000
22 |**`FBEnableDynamicCDCLK`**        | |0x200000
23 |**`FBUnknownFlag_400000`**        | |0x400000
24 |**`FBSupport5KSourceSize`**       | |0x800000

**SOURCE**: [**IntelFramebuffer.bt**](https://github.com/acidanthera/WhateverGreen/blob/master/Manual/IntelFramebuffer.bt)

Schöne Grüße

**Comment by webfalter** [comment]
Ich schaue es mir bei Gelegenheit mal an

**Comment by webfalter** [comment]
Sollte vom Grund her gehen, muss bloß noch paar andere Sachen beseitigen und ergänzen.
![Bildschirmfoto 2023-06-17 um 19 49 40](https://github.com/webfalter/OCToolBox/assets/481551/47e293a0-e1af-4cb2-accd-0ff9d50fb1b1)
![Bildschirmfoto 2023-06-17 um 19 49 46](https://github.com/webfalter/OCToolBox/assets/481551/0e944c2a-acbb-444f-8edc-f93db4161ac0)

**Comment by 5T33Z0** [comment]
Mega! Soll ich's testen? Ich frickle nämlich gerade an meinem patch um nen externen Monitor via HDMI auf DVI anzusteuern.

**Comment by webfalter** [comment]
Melde mich wenn es geht, muss erst noch paar Stellen umbauen.

**Comment by 5T33Z0** [comment]
Am Ende muss Little Endian bei rumkommen. Aber weißte ja sicher selbst ;)

**Comment by webfalter** [comment]
@5T33Z0 meldest Du Dich im HF wieder an, da können wir per PN schreiben. 👍

**Comment by 5T33Z0** [comment]
Nee, da melde ich mich nicht mehr an.
