### ISSUE TITLE
Anmerkungen Framebuffer und Connectors Calculator

### ISSUE THREAD

**Issue by 5T33Z0** [webfalter/OCToolBox#6]
Danke für das Update. Is gut geworden. Einige Probleme bestehen allerdings noch. Folgendes ist mir aufgefallen:

## Framebuffer

![Bildschirmfoto 2023-07-01 um 17 44 25](https://github.com/webfalter/OCToolBox/assets/76865553/ab2e35fb-6efc-4b5d-b8c9-837f6117dbf1)

Anmerkungen:
- Die Dezimal-Tabelle ist überflüssig
- Das Feld "Hexadecimal" sollte besser "Big Endian" heißen &rarr; technisch korrekter Begriff
- Das Feld "Hex Reversed" sollte besser Little Endian" heißen &rarr; technisch korrekter Begriff
- Das Feld "flags=" ist überflüssig, und inhaltlich falsch, da es den Big Endian Wert verwendet. Aber für die Config muss Little Endian verwendet werden. Also würde ich auf dieses Fled komplett verzichten. Es irritiertt nur, wenn man 3 felder hat, von denen 2 dasselbe zeigen, aber nur eines davon den Wert im richtigen Format enthält

## Connectors
![Bildschirmfoto 2023-07-01 um 17 44 31](https://github.com/webfalter/OCToolBox/assets/76865553/e4457cf2-d7e2-4bb9-b8e5-eb6736449647)

Für die Connectors Section gilt im Grunde dasselbe:
- Dezimal Tabelle fehlt. Der Einfachheit halber einfach die Decimal Tabelle in Frambuffer Section löschen für . Braucht man eh nicht.
- "Big Endian" statt "Hexadecimal"
- "Little Endian" Feld fehlt
- "flags" Feld überfüssig und falsches Format.

Schöne Grüße.

**Comment by 5T33Z0** [comment]
"Issue" einfach als "completed" schließen ist natürlich auch ne Lösung…

**Comment by webfalter** [comment]
dann schau mal auf das Label und habe einfach bissl Geduld. Wenn Du nicht im HF (**per PN**, sollst dort weder was schreiben noch mit sonst jemand kommunizieren) mit testen willst, hier lade ich keine extra Version hoch.

**Comment by 5T33Z0** [comment]
Mit "Next Version" als Label hätte ich was anfangen können.

Danke für das Update. Sieht gut aus.
